theme = "gruber_base16"
[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.indent-guides]
render = true
character = "â•Ž"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]
