theme = "gruber-darker"
[editor]
line-number = "relative"
color-modes = true
auto-pairs = false

[editor.indent-guides]
render = true
character = "â•"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-base-name"]
